### ISSUE TITLE
[Bug]: The Testcontainers overwritten wait strategy indicate readiness to early

### ISSUE THREAD

**Issue by HofmeisterAn** [egil/ApiTestingAZ#1]
Hi 👋, I noticed you're using Testcontainers in your demo project. I noticed a flaw in your configuration that I'd like to address to prevent potential issues with flakiness. Overriding the module's wait strategy is not recommended since modules are pre-configured. Typically, there's no need to override pre-configurations (except for database, username or password). Overwriting the wait strategy might lead to flakiness because ports are available earlier than the actual service.

https://github.com/egil/ApiTestingAZ/blob/91d3fba4c62a4eced1bcf17cd2ba5ca2abe7687d/TodoApi.Tests/AblaExtensions/TestContainersDatabaseAlbaExtension.cs#L47

The current configuration might indicate readiness too early. My suggestion is to stick to the module's default configuration.

BTW: Your configuration is equivalent to:

    _ = new MsSqlBuilder()
        .WithImage("mcr.microsoft.com/mssql/server:2022-latest")
        .WithPassword(SQLPASSWORD)
        .Build();

**Comment by egil** [comment]
Hey, thanks, I am no test container expert, just using it on a few projects, and the `.WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(SQLPORT))` seem to work.

What is the default strategy and what is the difference? Would love to learn more!

**Comment by HofmeisterAn** [comment]
The wait strategy essentially informs Testcontainers when the container is ready for use. This is when `StartAsync()` completes and your tests begin to run. If the wait strategy indicates readiness too early, your tests may fail, for instance, because the database is not yet fully operational.

The MSSQL [default wait strategy](https://github.com/testcontainers/testcontainers-dotnet/blob/e3be24f8256c21be4525e8abae623695c8bb7fb2/src/Testcontainers.MsSql/MsSqlBuilder.cs#L127-L144) waits until it establishes a database connection and successfully executes a query. The wait strategy can be as simple as [waiting for a log message](https://github.com/testcontainers/testcontainers-dotnet/blob/e3be24f8256c21be4525e8abae623695c8bb7fb2/src/Testcontainers.Oracle/OracleBuilder.cs#L78) or very complex, as in [this](https://github.com/testcontainers/testcontainers-dotnet/blob/e3be24f8256c21be4525e8abae623695c8bb7fb2/src/Testcontainers.Couchbase/CouchbaseBuilder.cs#L85-L124) configuration.

**Comment by egil** [comment]
Ahh, that makes complete sense to use that as a wait strategy. I was just googling and found some examples that used `.WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(SQLPORT))` so that's what I went with. I guess it may be an old suggestion that has been superseded by the `select 1` version.

**Comment by egil** [comment]
Thanks for bringing this to my attention and thanks for the awesome work with testcontainers

**Comment by HofmeisterAn** [comment]
> I was just googling and found some examples that used `.WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(SQLPORT))` so that's what I went with.

I know there are a few less-than-ideal examples out there, partly due to legacy implementations of the library. Whenever I come across them, I try to address them to prevent developers from running into issues (probably I should add the information to the [best practices](https://dotnet.testcontainers.org/api/best_practices/) too).

> Thanks for bringing this to my attention and thanks for the awesome work with testcontainers

Happy to help 🙏 Thanks.
